### ISSUE TITLE
Allow consecutive line comments

### ISSUE THREAD

**Issue by steel** [polleverywhere/js-config#5]
@nguyenj @adam-h we (@dannobytes and I) can't stand this rule. Please give us back our consecutive line comments!

https://github.com/polleverywhere/js-config/blob/982137f61fb074bf246ae690656dbead8b4dc87a/eslint-config/index.js#L22

**Comment by adam-h** [comment]
I'm happy for this to be relaxed.

**Comment by dannobytes** [comment]
Yes please.

On a related note, I'd like to propose we brainstorm and lock down a more
uniform set of style rules, conventions, best practices, etc and make this
an actual larger ongoing project. I'm interested in doing an overhaul of
our JS playbook and then updating our lint rules to reflect or help enforce
some more stricter guidelines.

**Comment by adam-h** [comment]
@dannobytes Sure, maybe open another issue with a proposal and we can discuss? I'd be wary of moving even further away from [standard JS](https://standardjs.com/) styles without a good reason though

**Comment by dannobytes** [comment]
Ah. I'm *all* for following an existing guideline. And StandardJS looks
perfect. I didn't know if we were following anything in particular other
than whats in Playbook. At the moment, I've not come across any internal
docs or references to StandardJS at all. So this is news to me.

Part of my proposal would be to put together a plan on how to actually
create better consistency according to StandardJS, make a list of what
rules we are currently not following, and organize some actions on how to
better enforce style consistency. My experience at the moment is that style
is loosely consistent with various exceptions and inconsistencies. Better
linting and precommits would be great and part of the goal.

**Comment by nguyenj** [comment]
I would actually like to move strictly to StandardJS, lets set up a time to discuss this soon.

**Comment by adam-h** [comment]
In theory, all of the code converted to es6 should be following our `eslint-config` from this repo. We only have 4 deviations from standard at the moment, basically everything in the [rules](https://github.com/polleverywhere/js-config/blob/982137f61fb074bf246ae690656dbead8b4dc87a/eslint-config/index.js#L14-L22) except `yoda` (not needed, we're resetting the default).

I'd be wary of changing any rule that can't be automatically "fixed" by eslint, otherwise it'll be a pain to update all of our code.

**Comment by dannobytes** [comment]
AFAIK, StandardJS does not specify any requirements for line comments. If we want to move towards full and strict StandardJS, exceptions like this make even less sense.

Does anyone know why this rule even exists? Removing this rule wouldn't cause any new errors to show up. So I'm not sure there's any real negative impact by having files in the repo that still contain /* multiline comments. The incentive here is to prevent this occurring in future commits moving forward.

**Comment by nguyenj** [comment]
not sure either but I’m on board switching this back to the default.

**Comment by dannobytes** [comment]
I'll create a PR b/c I'm excited to write // multi-line comments again :)

**Comment by adam-h** [comment]
Published as 1.2.0.
